### ISSUE TITLE
rireki.sty を LuaLaTeX で使えるようにするための提案です

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [shigio/rireki-style#3]
[shigio/rireki-style](https://github.com/shigio/rireki-style) で書いた履歴書を LuaLaTex でも組版できるようにしたいと思いまして `rrireki.sty` 冒頭の

```latex
\usepackage[dvipdfmx]{graphicx}
```

の部分をコメントアウトして外出しにすると

```latex
\documentclass[b5j]{ltjsarticle}
\usepackage[deluxe,nfssonly]{luatexja-preset}
\usepackage[luatex]{graphicx} % \usepackage{graphicx} でも可
\usepackage{rireki}
...
```

とすることで LuaLaTeX でも同等の出力が得られるようになりました。
ただし，これをしてしまうと，後方互換性が崩れるため，これまでの (u)pLaTeX での記述に手を加える必要が出てきます。

以下のブログ記事でも簡単に紹介しています。

- [LuaLaTeX でも履歴書を書きたい！ — しっぽのさきっちょ | text.Baldanders.info](https://text.baldanders.info/remark/2020/06/resume-with-lualatex/)

このリポジトリでは (u)pLaTeX のみの対応とするか LuaLaTeX へ拡張していいのか判断できませんでしたので，提案として挙げさせていただきます。
よろしくご検討くださいませ。

**Comment by shigio** [comment]
回答が遅くなってしまい、申し訳ありません。
ご提案の内容をさっそく反映させていただきました。

(使い方)
lualatex への切り替えには、以下のとおり、ファイルの一部書き換えが
必要になります。

lualatex で使用するには、rireki.tex の次のコメントを有効にします。

[rireki.tex]
...
%\lualatextrue
|
v
\lualatextrue

同じくMakefile をlualatex で使用するには、次のコメントを有効にします。

[Makefile]
...
#LATEX = lualatex
|
v
LATEX = lualatex

ご提案とコード、ありがとうございました。

**Comment by spiegel-im-spiegel** [comment]
対応していただき，ありがとうございます。この Issue はクローズしますね。
